apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: my-StatefulSet
spec:
  replicas: 3
  selector:
    matchlabels:
      app: my-app
  template: 
    matadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginix
        ports:
        -containerPort: 80