apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: dev-team
spec:
  hard:
    requests.storage: 100Gi
    gp2.storageclass.storage.k8s.io/requests.storage: 50Gi
    persistentvolumeclaims: "10"