apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution: # Hard / required
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In 
            values:
            - test
  containers:
  - name: co1
    image: nginx
    ports:
    - containerPort: 8080