apiVersion: v1
kind: Pod 
metadata: 
  name: my-app 
spec: 
  containers:
  - name: co1
    images: nginx
    ports: 
    - containerPorts: 8080
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username 
    - name: password
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password