apiVersion: v1
kind: Pod
metadata:
  name: livenessprob
spec:
  containers:
  - name: co1
    image: busybox
    args:
      - /bin/sh
      - -c 
      - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 50
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3